apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: dev
            namespace: nginx-dev
            valuesFile: values/nginx/dev.yaml
          - name: test
            namespace: nginx-staging
            valuesFile: values/nginx/test.yaml
          - name: int
            namespace: nginx-prod
            valuesFile: values/nginx/int.yaml

  template:
    metadata:
      name: nginx-{{name}}
    spec:
      project: default

      source:
        repoURL: https://github.com/zedrazer/argocd-kind.git
        targetRevision: main
        path: charts/nginx
        helm:
          valueFiles:
            - "{{valuesFile}}"

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
