service:
  type: ClusterIP

pactbroker:
  baseUrl: http://pact-broker
  logLevel: INFO

  database:
    type: postgres
    host: postgres.platform.svc.cluster.local
    port: 5432
    name: pactbroker
    username: pactbroker
    password: pactbroker

auth:
  enabled: true
  username: admin
  password: admin
