# Minimal dev configuration for Argo CD
service:
  type: ClusterIP

pactbroker:
  logLevel: INFO
  baseUrl: http://pact-broker

  # Use SQLite for dev
  database:
    type: sqlite
  sqlite:
    enabled: true

  webhooks:
    enabled: false

  auth:
    enabled: true
    existingSecret: pact-broker-auth
    usernameKey: username
    passwordKey: password

# Optional: keep replicas at 1 for dev
replicaCount: 1

# Optional: no ingress for dev
ingress:
  enabled: false