image:
  repository: bitnami/postgresql
  tag: latest

auth:
  postgresPassword: postgres
  username: pactbroker
  database: pactbroker
  existingSecret: "pact-broker-postgres-secret"
  secretKeys:
    adminPasswordKey: postgresPassword
    userPasswordKey: userPassword

primary:
  persistence:
    enabled: false
