apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/zedrazer/argocd-kind.git
    targetRevision: main
    path: charts/postgresql
    helm:
      valueFiles:
        - ../../values/postgres/values.yaml
      parameters:
        - name: fullnameOverride
          value: postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true